apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Namespace }}
  name: locust-main-{{ .LocustName }}
{{- with .Service.Annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: locust-main-{{ .LocustName }}
    role: main
{{- with .Service.Labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ports:
    - port: {{ .Service.Port }}
      targetPort: loc-main-web
      protocol: TCP
      name: loc-main-web
    - port: 5557
      targetPort: loc-main-p1
      protocol: TCP
      name: loc-main-p1
    - port: 5558
      targetPort: loc-main-p2
      protocol: TCP
      name: loc-main-p2
  selector:
    app: locust-main-{{ .LocustName }}
  type: NodePort
