{{- if .Ingress.Class -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: {{ .Namespace }}
  name: locust-main-{{ .LocustName }}
  annotations:
    {{- if eq .Ingress.Class "alb" }}
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: {{ .Ingress.ALB.Scheme }}
      alb.ingress.kubernetes.io/security-groups: {{ .Ingress.ALB.SecurityGroups }}
      {{- if .Ingress.ALB.CertificateARN }}
      alb.ingress.kubernetes.io/certificate-arn: {{ .Ingress.ALB.CertificateARN }}
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      {{- else }}
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
      {{- end }}
    {{- else }}
      kubernetes.io/ingress.class: nginx
      nginx.org/proxy-connect-timeout: "30s"
      nginx.org/proxy-read-timeout: "20s"
      nginx.org/client-max-body-size: "4m"
    {{- end }}
{{- with .Ingress.Annotations }}
{{ toYaml . | indent 6 }}
{{- end }}
  labels:
    app: locust-main-{{.LocustName}}
{{- with .Ingress.Labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    - host: {{ .Ingress.Host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: locust-main-{{ .LocustName }}
              servicePort: {{ .Service.Port }}
{{- end -}}
