# {{.LocustName}}-klocust.yaml kloucst config file
namespace: {{ .Namespace }}
locustName: {{ .LocustName }}

configmap:
  locustFilename: {{ .LocustName }}-locustfile.py

main:
  requests:
    cpu: {{ .Main.Requests.CPU | default "250m" }}
    memory: {{ .Main.Requests.Memory | default "512Mi" }}
  limits:
    cpu: {{ .Main.Limits.CPU | default "250m" }}
    memory: {{ .Main.Limits.Memory | default "512Mi" }}
  nodeSelector: {}
#   env: dev
#   app: locust
  tolerations: []
#   - key: "example-key"
#     operator: "Exists"
#     effect: "NoSchedule"
  affinity: {}
  labels: {}
  annotations: {}

worker:
  count: {{ .Worker.Count | default 1 }}
  requests:
    cpu: {{ .Worker.Requests.CPU | default "250m" }}
    memory: {{ .Worker.Requests.Memory | default "512Mi" }}
  limits:
    cpu: {{ .Worker.Limits.CPU | default "250m" }}
    memory: {{ .Worker.Limits.Memory | default "512Mi" }}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  labels: {}
  annotations: {}

service:
  port: 8089
  labels: {}
{{- if .Service.EnableFargate }}
  annotations:
    # For EKS on Fargate
    alb.ingress.kubernetes.io/target-type: ip
{{- else }}
  annotations: {}
    # For EKS on Fargate
    #alb.ingress.kubernetes.io/target-type: ip
{{ end }}

{{- if .Ingress.Class }}
ingress:
  class: {{ .Ingress.Class }}
  host: locust-{{ .LocustName }}.{{ .Ingress.Host | default "example.com" }}
  {{- if eq .Ingress.Class "alb" }}
  alb:
    scheme: {{ .Ingress.ALB.Scheme | default "internal" }}
    securityGroups: {{ .Ingress.ALB.SecurityGroups }}
    certificateARN: {{ .Ingress.ALB.CertificateARN }}
  {{- end }}
  labels: {}
  annotations: {}
{{- end }}

# example of nginx ingress
#ingress:
#  class: nginx
#  host: locust-{{ .LocustName }}.example.com
#  labels: {}
#  annotations: {}

# example of ALB example
#ingress:
#  class: alb
#  host: locust-{{ .LocustName }}.example.com
#  alb:
#    scheme: internal
#    securityGroups: sg-abcd1234, sg-defg1234
#    certificateARN: arn:aws:acm:ap-northeast-2:000:cerficiate/xxx-xxx-xxxx
#  labels: {}
#  annotations: {}
